--Book(도서) 테이블 생성
CREATE TABLE BookInfo
(
	ID			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	BookName	TEXT NOT NULL,
	BookISBN	TEXT
);

--User(사용자) 테이블 생성
CREATE TABLE UserInfo
(
	ID			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name		TEXT NOT NULL,
	PhoneNum	TEXT
);

DROP TABLE Book;
DROP TABLE User;
